### ISSUE TITLE
document inter tool xml format

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#15]

**Comment by geryxyz** [comment]
the description need to contain and explain the differences between mapping-to-placing and placing-to-rendering xmls. it also need to show at least one example for each of these. besides that put a link to the xml schema as definition: https://github.com/geryxyz/CodeMetropolis/blob/master/sources/codemetropolis-toolchain-commons/src/main/resources/cmxml_scheme.xsd

**Comment by geryxyz** [comment]
"As you can see on the following example, only position differs in these two XMLs."
this is not true

during placing phase, the postiion of simple elements (which does not contain any other element) are set and the size of the compound elements are calculated and propagated up along the containment relation. of course the position of the compound elements are also updated.

> for example in a garden place (set the position of) two garden in the two opposite corner, then the garden should scaled up (set the size) to be able to contain these floors.

**Comment by brita-sed** [comment]
I corrected it and hope it's now finished.
