### ISSUE TITLE
Any executable file can be selected and run without pre-checking

### ISSUE THREAD

**Issue by SzatmariA** [geryxyz/CodeMetropolis#190]
Running the CM GUI you can specify the SourceMeter exe file, however you can select any exe you'd like. The metric generation starts, i.e. starting the executable file. Even though the program checks whether the metric generation was successful, it wastes resources by running the other one. This is bad practice.
Probably a pre-check on whether it is the right exe could solve the issue easily.

**Comment by szatma** [comment]
#285
