### ISSUE TITLE
Graphical Mapping XML editor

### ISSUE THREAD

**Issue by aadamv** [geryxyz/CodeMetropolis#251]
**Current behavior:** Currently the user cannot edit the mapping file but in XML

**Expected behavior:** The user can create the mapping file in the UI.
There should be a new button next to the path of the mapping.xml input field, which brings up the editor in a new window.
Users can add and remove linkings and bindings in a list. Drop-down should be supported.
Binding sources, methods, targets, levels, values, and all list-like values must be chosen from a dropdown input field.
The users need to be able to change or remove the already added linkings or bindings. We prefer a minimalist design for the UI. After closing the editor window or clicking the `Save and use` button a "save as..." dialog should appear. If the file is saved successfully its path should be automatically inserted into the mapping.xml input field on the main window. If the user chooses the cancel button on the dialog the editor and the dialog should be closed without any further changes.

The details of the mapping file format could be found here: http://codemetropolis.github.io/CodeMetropolis/toolchain/mapping/

You may need to reverse engineer some properties of the format from examples or from the source code itself.

**Comment by geryxyz** [comment]
duplicated: #236
