### ISSUE TITLE
Logs should be generated or explicitly said where they are

### ISSUE THREAD

**Issue by SzatmariA** [geryxyz/CodeMetropolis#279]
I tried using the world generation through the GUI. I provided paths and data that I believe were right. However, whenever I click the generate button a window pops up saying "World generation failed. Check logs for details!"

![image](https://user-images.githubusercontent.com/17518412/149675062-2942dd03-f06d-403f-b673-c0fc716d558f.png)

I thought the logs would be saved to the same folder and there were some logs earlier however it stopped working

![image](https://user-images.githubusercontent.com/17518412/149675132-82032b6c-af2b-48d1-a102-488f59ce796b.png)

**Comment by szatma** [comment]
This was due to problems with Sourcemeter, I will close this issue since it does not affect CodeMetropolis
