### ISSUE TITLE
Generate Book and Quill for each building

### ISSUE THREAD

**Issue by SzatmariA** [geryxyz/CodeMetropolis#289]
A book and quill in Minecraft is an item used to write written books.
This would come in handy at giving textual information about the building to the user. E.g. Name of the building: Sources. LLOC: 34.
This book would be dropped near the name table of the buildings, hence the user could collect them and read them anytime.

Steps to complete this task:

1. Integrate book and quill in to CodeMetropolis
2. Write name and useful information into the book (metrics like LLOC, McCC, MI)
3. Generate it into the world

**Comment by szatma** [comment]
#210
