### ISSUE TITLE
Put balloons on the fence of the gardens

### ISSUE THREAD

**Issue by SzatmariA** [geryxyz/CodeMetropolis#298]
In Minecraft, there are several balloons. See the link for further information: https://minecraft.fandom.com/wiki/Balloon
These balloons have different colours. 
Attaching them to the fences could be an indicator of outlier/dangerous metrics. 
E.g. a method has a high number of McCC should have red balloons on the garden's fence.

**Comment by szatma** [comment]
Only in educational edition
