### ISSUE TITLE
World copy should be automated

### ISSUE THREAD

**Issue by SzatmariA** [geryxyz/CodeMetropolis#305]
Using the GUI, when you generate the world, the end step should be that the world is automatically copied to the saves folder.
There should be a pop-up window at the end that asks the user whether they want the Minecraft world to be copied in the saves folder.

Guidance to complete the task:

1.  Use the Minecraft root (path) string from the GUI
2. After the generation is successful create a pop-up window that asks the user whether they want the world to be copied
3. If they click yes, then copy the folder, if no then return

**Comment by szatma** [comment]
I could not reproduce this issue
