### ISSUE TITLE
add support for interchangeable mapping targets

### ISSUE THREAD

**Issue by blip24** [geryxyz/CodeMetropolis#38]

**Comment by geryxyz** [comment]
**must have**
warn if multiple elements are mapped to the same object
error if multiple properties are mapped to the same visual prop
validate buildable structure along containment relation (garden in floor is BAD)
check if visual element has the requested property
warn for default fallback to default value

**nice to have**
store CDF and Mapping file line info in buildables to provide usable error message for user
