### ISSUE TITLE
put every cmd or code related part into inline or block code

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#51]
mark everything that you have to write in a command line or copied from a source file, https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
(on hungarian keyboard the inline code tick is alt gr + 7)

example:
`-projectName=<inputProjectName>` The name of the project. It will be the name of the directory in the results directory

```dos
SourceMeterJava.exe -projectName=<inputProjectName> -projectBaseDir=<inputProjectDir> -resultsDir=<ResultsDir>
```

**Comment by brita-sed** [comment]
I corrected it in About, Mapping, Placing and Rendering Tool page.
