### ISSUE TITLE
investigate SonarQube 500 limit

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#54]
https://jira.sonarsource.com/browse/SONAR-2920?jql=text%20~%20%22500%22
https://groups.google.com/forum/#!searchin/sonarqube/500/sonarqube/Hj99CE2_nLE/ZxpJba_PEAAJ

**Comment by blip24** [comment]
https://nemo.sonarqube.org/api_documentation/api/metrics
(GET api/metrics/search)

according to this doc the page size and page number can be specified in parameters (p, ps)

**Comment by geryxyz** [comment]
http://10.6.13.7:9000/api/resources?scopes=FIL,DIR,PRJ&format=xml

it give more then 500 <resource> tag so either
* they fix it
* or increase the maximum size

**Comment by geryxyz** [comment]
p= and ps= parameters are still ignored

tested on SonarQube Version 5.3

**Comment by geryxyz** [comment]
check it for more resources

**Comment by geryxyz** [comment]
I am able to get more 2000 resources, paging still missing for resources
