### ISSUE TITLE
navigation in the generated city [2PW]

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#76]
**Estimated resource: 2PW**
The goal is to provide an easy way to navigate in the city. It will be implemented via commands that let the player jump to various location based on the structure of visualized data (for example the package hierarchy). Depending on the available development resource an optional minimap and basic user interface will be also implemented.

**Comment by brita-sed** [comment]
On the top side of the screen the map of the city would appear, with the signed position of the user with a minecraft man icon.
On the bottom side of the screen, the user could search by giving a string value (looking for method, class etc.)
![issue76_search_jump](https://cloud.githubusercontent.com/assets/16755484/13879193/73324372-ed16-11e5-851f-b5fba649add1.jpg)
