### ISSUE TITLE
two way navigation via sonar

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#79]

**Comment by brita-sed** [comment]
Back to SonarQube button on the topright of the screen: 
![issue79_backtosonar_cm](https://cloud.githubusercontent.com/assets/16755484/13878659/20e30de8-ed13-11e5-8396-6962021348aa.jpg)
Go to MineCraft world button in the end of the bottom side menu:
![issue79_gotominecraft](https://cloud.githubusercontent.com/assets/16755484/13878733/8b9e4b66-ed13-11e5-9a5e-f6657648b653.jpg)

**Comment by geryxyz** [comment]
split: #89 #88
