### ISSUE TITLE
new value conversions for properties

### ISSUE THREAD

**Issue by geryxyz** [geryxyz/CodeMetropolis#82]
for example
- constant multiplication or scale
- log scale
- enhanced normalization with custom upper and lower bounds
- new range based mapping from continous values to discrete ones

**Comment by brita-sed** [comment]
Normal city:
![issue82_epuletek_normal](https://cloud.githubusercontent.com/assets/16755484/13877755/2d5e4818-ed0d-11e5-8bc3-859d49bfd886.jpg)
Contant multiplication with 0.5:
![issue82_epuletek_scale05](https://cloud.githubusercontent.com/assets/16755484/13877768/38b58fbe-ed0d-11e5-97e4-da3f6148b957.jpg)

**Comment by geryxyz** [comment]
#99
